version: '3'

tasks:
    setup-dev:
        desc: Sets up your local development virtual environment.
        cmds:
            - python -m venv .venv
            - .venv/bin/pip install -r requirements-dev.txt
            - .venv/bin/python setup.py develop
            - echo 'Virtual Environment (dev) setup.'
            
